######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 16 22:22:42 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
