######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 16 22:34:42 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editor.h
SOURCES += editor.cpp main.cpp
