######################################################################
# Automatically generated by qmake (3.1) Mon Apr 24 10:25:02 2017
######################################################################

TEMPLATE = app
TARGET = transcription
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += editor.h
SOURCES += editor.cpp main.cpp
